// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/phamphihungbk/go-graphql/app"
	"github.com/phamphihungbk/go-graphql/app/controllers"
	"github.com/phamphihungbk/go-graphql/configs"
	"github.com/phamphihungbk/go-graphql/database"
	"github.com/phamphihungbk/go-graphql/src/repositories"
	"github.com/phamphihungbk/go-graphql/src/services"
)

// Injectors from wire.go:

func InitializeApp(dbCfg *configs.DBCfg) (*Application, error) {
	db := database.NewDBConnection(dbCfg)
	userRepositoryInterface := repositories.NewUserRepository(db)
	userServiceInterface := services.NewUserService(userRepositoryInterface)
	userController := controllers.NewUserController(userServiceInterface)
	engine := app.NewRouter(userController)
	application := NewApplication(engine)
	return application, nil
}
