// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package server

import (
	"github.com/phamphihungbk/go-graphql/config"
	"github.com/phamphihungbk/go-graphql/internal/app"
	"github.com/phamphihungbk/go-graphql/internal/repository"
	"github.com/phamphihungbk/go-graphql/internal/resolver"
	"github.com/phamphihungbk/go-graphql/internal/service"
)

// Injectors from wire.go:

func InitializeApp(dbCfg *config.DBCfg) (*Application, error) {
	db := app.NewDBConnection(dbCfg)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userResolver := resolver.NewUserResolver(userService)
	engine := app.NewRoute(userResolver)
	application := NewApplication(engine)
	return application, nil
}
